dev_mode: false
tls:
  enabled: false
  key:     "foo"
  cert:    "bar"

cors:
  origins:
    - http://localhost
  headers:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS

database:
  type: mongo
  mongo:
    database: api
    collection: payments
    uri: user:password@localhost
