dev_mode: false
tls:
  enabled: true
  key:     "tls_test/key.pem"
  cert:    "tls_test/certificate.pem"

cors:
  origins:
    - http://localhost
  headers:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS

database:
  type: mongo
  mongo:
    database: api
    collection: payments
    uri: user:!PassWD!@localhost
