dev_mode: false
tls:
  enabled: false
  key:     "tls_test/key.pem"
  cert:    "tls_test/certificate.pem"

cors:
  origins:
    - '*'
  headers:
    - '*'
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS

database:
  type: mongo
  mongo:
    database: api
    collection: payments
    uri: user:password@localhost
